### ISSUE TITLE
Add new script to make CI lint action happy

### ISSUE THREAD

**Issue by tcnghia** [chainguard-dev/go-grpc-kit#17]
It seems there are some upstream change in chainguard actions that need a new bash script. This is now failing for all the PRs.

**Comment by tcnghia** [comment]
cc @cpanato

**Comment by tcnghia** [comment]
cc @k4leung4

**Comment by cpanato** [comment]
will work on that

**Comment by tcnghia** [comment]
@k4leung4 fixed it in #15
